name: 'TypeScript Error Reporter'
description: 'TS compiler diagnostics reporter'
author: 'andoshin11'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'blue'
